version: '3.8'

services:
  agent-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-frontend
    ports:
      - "80:80"
      - "443:443"  # 如果需要HTTPS
    environment:
      - NODE_ENV=production
    volumes:
      # 可选：挂载日志目录
      - ./logs:/var/log/nginx
      # 可选：挂载SSL证书（如果使用HTTPS）
      # - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    networks:
      - agent-network
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加监控服务
  # nginx-exporter:
  #   image: nginx/nginx-prometheus-exporter:latest
  #   container_name: nginx-exporter
  #   ports:
  #     - "9113:9113"
  #   command:
  #     - -nginx.scrape-uri=http://agent-frontend/nginx_status
  #   depends_on:
  #     - agent-frontend
  #   networks:
  #     - agent-network

networks:
  agent-network:
    driver: bridge

volumes:
  logs:
